export type RoleKey =
  | "SUPER_ADMIN"
  | "CLINIC_OWNER"
  | "BRANCH_MANAGER"
  | "DENTIST"
  | "DENTAL_ASSISTANT"
  | "RECEPTIONIST"
  | "ACCOUNTANT"
  | "LAB_TECHNICIAN"
  | "PHARMACIST"
  | "INVENTORY_MANAGER"

export const MODULES = [
  "dashboard",
  "patients",
  "appointments",
  "waitingRoom",
  "clinical",
  "dentalChart",
  "diagnoses",
  "treatmentPlans",
  "prescriptions",
  "imaging",
  "documents",
  "consents",
  "billing",
  "invoices",
  "payments",
  "installments",
  "expenses",
  "inventory",
  "suppliers",
  "laboratory",
  "staff",
  "dentists",
  "roles",
  "reports",
  "settings",
  "notifications",
  "audit",
] as const

export const ACTIONS = ["view", "create", "edit", "delete", "export", "print", "approve", "refund"] as const

export type Permission =
  | `${(typeof MODULES)[number]}:${(typeof ACTIONS)[number]}`
  | "docs:view"
  | "docs:create"
  | "docs:delete"
  | "clinic:manage"

export const ALL_PERMISSIONS: Permission[] = [
  "dashboard:view",
  "patients:view",
  "patients:create",
  "patients:edit",
  "patients:delete",
  "patients:export",
  "patients:print",
  "appointments:view",
  "appointments:create",
  "appointments:edit",
  "appointments:delete",
  "appointments:export",
  "appointments:print",
  "waitingRoom:view",
  "waitingRoom:create",
  "waitingRoom:edit",
  "clinical:view",
  "clinical:create",
  "clinical:edit",
  "dentalChart:view",
  "dentalChart:create",
  "dentalChart:edit",
  "diagnoses:view",
  "diagnoses:create",
  "diagnoses:edit",
  "diagnoses:delete",
  "treatmentPlans:view",
  "treatmentPlans:create",
  "treatmentPlans:edit",
  "treatmentPlans:approve",
  "prescriptions:view",
  "prescriptions:create",
  "prescriptions:edit",
  "prescriptions:print",
  "imaging:view",
  "imaging:create",
  "imaging:delete",
  "docs:view",
  "docs:create",
  "docs:delete",
  "consents:view",
  "consents:create",
  "consents:print",
  "billing:view",
  "invoices:view",
  "invoices:create",
  "invoices:edit",
  "invoices:delete",
  "invoices:print",
  "invoices:refund",
  "payments:view",
  "payments:create",
  "payments:refund",
  "installments:view",
  "installments:create",
  "installments:edit",
  "expenses:view",
  "expenses:create",
  "expenses:edit",
  "expenses:delete",
  "inventory:view",
  "inventory:create",
  "inventory:edit",
  "inventory:delete",
  "suppliers:view",
  "suppliers:create",
  "suppliers:edit",
  "laboratory:view",
  "laboratory:create",
  "laboratory:edit",
  "laboratory:delete",
  "staff:view",
  "staff:create",
  "staff:edit",
  "staff:delete",
  "dentists:view",
  "dentists:create",
  "dentists:edit",
  "roles:view",
  "roles:create",
  "roles:edit",
  "reports:view",
  "reports:export",
  "settings:view",
  "clinic:manage",
  "notifications:view",
  "audit:view",
]

export const ROLE_DEFINITIONS: Record<RoleKey, { name: string; nameAr: string; permissions: Permission[] }> = {
  SUPER_ADMIN: {
    name: "Super Admin",
    nameAr: "مدير النظام",
    permissions: ALL_PERMISSIONS,
  },
  CLINIC_OWNER: {
    name: "Clinic Owner",
    nameAr: "مالك العيادة",
    permissions: [
      "dashboard:view",
      "patients:view", "patients:create", "patients:edit", "patients:export", "patients:print",
      "appointments:view", "appointments:create", "appointments:edit", "appointments:export", "appointments:print",
      "waitingRoom:view", "waitingRoom:create", "waitingRoom:edit",
      "clinical:view", "clinical:create", "clinical:edit",
      "dentalChart:view", "dentalChart:create", "dentalChart:edit",
      "diagnoses:view", "diagnoses:create", "diagnoses:edit",
      "treatmentPlans:view", "treatmentPlans:create", "treatmentPlans:edit", "treatmentPlans:approve",
      "prescriptions:view", "prescriptions:create", "prescriptions:edit", "prescriptions:print",
      "imaging:view", "imaging:create", "imaging:delete",
      "docs:view", "docs:create", "docs:delete",
      "consents:view", "consents:create", "consents:print",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:edit", "invoices:print", "invoices:refund",
      "payments:view", "payments:create", "payments:refund",
      "installments:view", "installments:create", "installments:edit",
      "expenses:view", "expenses:create", "expenses:edit", "expenses:delete",
      "inventory:view", "inventory:create", "inventory:edit",
      "suppliers:view", "suppliers:create", "suppliers:edit",
      "laboratory:view", "laboratory:create", "laboratory:edit",
      "staff:view", "staff:create", "staff:edit",
      "dentists:view", "dentists:create", "dentists:edit",
      "roles:view", "roles:edit",
      "reports:view", "reports:export",
      "settings:view", "clinic:manage",
      "notifications:view",
      "audit:view",
    ],
  },
  BRANCH_MANAGER: {
    name: "Branch Manager",
    nameAr: "مدير فرع",
    permissions: [
      "dashboard:view",
      "patients:view", "patients:create", "patients:edit", "patients:export", "patients:print",
      "appointments:view", "appointments:create", "appointments:edit", "appointments:export", "appointments:print",
      "waitingRoom:view", "waitingRoom:create", "waitingRoom:edit",
      "clinical:view", "clinical:create", "clinical:edit",
      "dentalChart:view", "dentalChart:create", "dentalChart:edit",
      "diagnoses:view", "diagnoses:create", "diagnoses:edit",
      "treatmentPlans:view", "treatmentPlans:create", "treatmentPlans:edit", "treatmentPlans:approve",
      "prescriptions:view", "prescriptions:create", "prescriptions:edit", "prescriptions:print",
      "imaging:view", "imaging:create",
      "docs:view", "docs:create",
      "consents:view", "consents:create", "consents:print",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:edit", "invoices:print", "invoices:refund",
      "payments:view", "payments:create", "payments:refund",
      "installments:view", "installments:create", "installments:edit",
      "expenses:view", "expenses:create", "expenses:edit", "expenses:delete",
      "inventory:view", "inventory:create", "inventory:edit",
      "suppliers:view", "suppliers:create", "suppliers:edit",
      "laboratory:view", "laboratory:create", "laboratory:edit",
      "staff:view",
      "dentists:view",
      "reports:view", "reports:export",
      "settings:view",
      "notifications:view",
      "audit:view",
    ],
  },
  DENTIST: {
    name: "Dentist",
    nameAr: "طبيب أسنان",
    permissions: [
      "dashboard:view",
      "patients:view", "patients:create", "patients:edit", "patients:print",
      "appointments:view", "appointments:create", "appointments:edit",
      "waitingRoom:view", "waitingRoom:create", "waitingRoom:edit",
      "clinical:view", "clinical:create", "clinical:edit",
      "dentalChart:view", "dentalChart:create", "dentalChart:edit",
      "diagnoses:view", "diagnoses:create", "diagnoses:edit", "diagnoses:delete",
      "treatmentPlans:view", "treatmentPlans:create", "treatmentPlans:edit",
      "prescriptions:view", "prescriptions:create", "prescriptions:edit", "prescriptions:print",
      "imaging:view", "imaging:create",
      "docs:view", "docs:create",
      "consents:view", "consents:create", "consents:print",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:print",
      "payments:view",
      "installments:view",
      "laboratory:view", "laboratory:create", "laboratory:edit",
      "reports:view",
      "notifications:view",
    ],
  },
  DENTAL_ASSISTANT: {
    name: "Dental Assistant",
    nameAr: "مساعد طبيب أسنان",
    permissions: [
      "dashboard:view",
      "patients:view", "patients:create", "patients:edit",
      "appointments:view", "appointments:create", "appointments:edit",
      "waitingRoom:view", "waitingRoom:create", "waitingRoom:edit",
      "clinical:view", "clinical:create",
      "dentalChart:view", "dentalChart:create",
      "diagnoses:view",
      "treatmentPlans:view",
      "prescriptions:view",
      "imaging:view", "imaging:create",
      "docs:view", "docs:create",
      "consents:view", "consents:create",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:print",
      "notifications:view",
    ],
  },
  RECEPTIONIST: {
    name: "Receptionist",
    nameAr: "استقبال",
    permissions: [
      "dashboard:view",
      "patients:view", "patients:create", "patients:edit", "patients:export", "patients:print",
      "appointments:view", "appointments:create", "appointments:edit", "appointments:delete", "appointments:export", "appointments:print",
      "waitingRoom:view", "waitingRoom:create", "waitingRoom:edit",
      "clinical:view",
      "dentalChart:view",
      "diagnoses:view",
      "treatmentPlans:view",
      "prescriptions:view", "prescriptions:print",
      "imaging:view",
      "docs:view", "docs:create",
      "consents:view", "consents:create", "consents:print",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:print",
      "payments:view", "payments:create",
      "installments:view",
      "notifications:view",
    ],
  },
  ACCOUNTANT: {
    name: "Accountant",
    nameAr: "محاسب",
    permissions: [
      "dashboard:view",
      "patients:view",
      "appointments:view",
      "billing:view",
      "invoices:view", "invoices:create", "invoices:edit", "invoices:print", "invoices:refund",
      "payments:view", "payments:create", "payments:refund",
      "installments:view", "installments:create", "installments:edit",
      "expenses:view", "expenses:create", "expenses:edit", "expenses:delete",
      "reports:view", "reports:export",
      "notifications:view",
    ],
  },
  LAB_TECHNICIAN: {
    name: "Lab Technician",
    nameAr: "فني مختبر",
    permissions: [
      "dashboard:view",
      "patients:view",
      "laboratory:view", "laboratory:create", "laboratory:edit", "laboratory:delete",
      "imaging:view",
      "docs:view",
      "notifications:view",
    ],
  },
  PHARMACIST: {
    name: "Pharmacist",
    nameAr: "صيدلي",
    permissions: [
      "dashboard:view",
      "patients:view",
      "prescriptions:view", "prescriptions:create", "prescriptions:print",
      "inventory:view",
      "inventory:create", "inventory:edit", "inventory:delete",
      "suppliers:view", "suppliers:create", "suppliers:edit",
      "notifications:view",
    ],
  },
  INVENTORY_MANAGER: {
    name: "Inventory Manager",
    nameAr: "مدير المخزون",
    permissions: [
      "dashboard:view",
      "inventory:view", "inventory:create", "inventory:edit", "inventory:delete",
      "suppliers:view", "suppliers:create", "suppliers:edit",
      "expenses:view",
      "reports:view",
      "notifications:view",
    ],
  },
}

export const ROLE_KEYS = Object.keys(ROLE_DEFINITIONS) as RoleKey[]

export function defaultPermissionsFor(roleKey: RoleKey): Permission[] {
  return ROLE_DEFINITIONS[roleKey].permissions
}